### ISSUE TITLE
Character Controller

### ISSUE THREAD

**Issue by j-scheid** [xXM1M1stYLeXx/AgathePower#4]

**Comment by JulianSeibert99** [comment]
Bug noch fixen dass Player unterschiedlich schnell ist

**Comment by stemmi99** [comment]
Der Bug kommt wahrscheinlich davon, dass wenn man "schräg" läuft sich der Input von z.B. hoch und links addiert und dadurch ist man schneller

**Comment by JulianSeibert99** [comment]
Bug gefixed
